[target.riscv32imc-unknown-none-elf]
runner = "espflash flash --monitor --partition-table=partitions.csv"
rustflags = ["-C", "link-arg=-Tlinkall.x"]

[build]
target = "riscv32imc-unknown-none-elf"

[unstable]
build-std = ["core", "alloc"]

[env]
ESP_LOG = "INFO"
